apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-ingress
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   if ($http_origin ~* "^https?://((?:www\.exactmatch\.com)|(?:.*\.regexmatch\.com))$") {
    #     set $cors "true";
    #   }
    #   if ($request_method = 'OPTIONS') {
    #     set $cors "${cors}options";
    #   }

    #   if ($cors = "true") {
    #     add_header 'Access-Control-Allow-Origin' "$http_origin" always;
    #     add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, PATCH, OPTIONS' always;
    #     add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization' always;
    #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    #   }

    #   if ($cors = "trueoptions") {
    #     add_header 'Access-Control-Allow-Origin' "$http_origin";
    #     add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, PATCH, OPTIONS';
    #     add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
    #     add_header 'Access-Control-Max-Age' 1728000;
    #     add_header 'Content-Type' 'text/plain charset=UTF-8';
    #     add_header 'Content-Length' 0;
    #     return 204;
    #   }
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    # more_set_headers "Access-Control-Allow-Origin: $http_origin";
spec:
  rules:
    # - host: mylocalhost.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-services
                port:
                  number: 8080
