apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laravel-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
                serviceName: laravel-services
                servicePort: 80