apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  selector:
    matchLabels:
      app: podlaravel
  template:
    metadata:
      labels:
        app: podlaravel
    spec:
      containers:
      - name: podlaravel
        image: juliocesarjcrs/laravel
        env:
            - name: APP_NAME
              value: modificando-pod
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
