apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysqlpod
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlpod
    spec:
      containers:
      - name: mysqlpod
        image: mysql:5.7.22
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: "laravel"
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_PASSWORD
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            value: "root"

