apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueapp-deployment
spec:
  selector:
    matchLabels:
      app: vueapp
  template:
    metadata:
      labels:
        app: vueapp
    spec:
      containers:
      - name: vueapp
        image: juliocesarjcrs/vueapp
        resources:
          limits:
            memory: "500Mi"
            cpu: "800m"
        ports:
        - containerPort: 8080
